"""Emit CREATE INDEX statements for indexes declared in the schemas.

``create_db_and_tables()`` builds declared indexes on a *fresh* database, because
they reach SQLAlchemy through ``__table_args__``. It does nothing for a database
that already exists: ``create_all`` creates what is missing and never alters or
drops. This file closes that gap -- run it against a live database and the
declared indexes appear.

It is deliberately create-only. Removing an ``index:`` from a schema will not drop
anything, because a declarative schema cannot express "this index must not exist".
Dropping one stays a hand-written migration.
"""

import logging
from os import PathLike

from .schema_context import SchemaContext

logger = logging.getLogger(__name__)


class indexes:
    _indexes_logger = logging.getLogger(__name__).getChild(__qualname__)

    def __init__(self, folder: str | PathLike):
        self._ctx = SchemaContext(folder)
        self.folder = str(folder)
        self.logger = logging.getLogger(__name__).getChild(self.__class__.__name__)
        self.logger.info(f"Building index DDL from schemas in {folder}")

    def build(self) -> "indexes":
        self.specs: list[dict] = []
        for filename in self._ctx.filenames:
            foreign_keys = set(self._ctx.foreign_keys_of(filename))
            for spec in self._ctx.index_specs_of(filename):
                # Foreign key columns are already indexed by the generated model.
                if spec["column"] in foreign_keys:
                    continue
                self.specs.append(spec)
        self.logger.info(f"{len(self.specs)} declared index(es)")
        return self

    def statements(self) -> list[str]:
        out = []
        for spec in self.specs:
            using = f" USING {spec['method']}" if spec["method"] else ""
            out.append(
                f"CREATE INDEX IF NOT EXISTS {spec['name']} "
                f"ON {spec['table']}{using} ({spec['column']});"
            )
        return out

    def render(self) -> str:
        header = (
            "-- indexes.sql -- generated by fastapifromfrictionless. Do not edit.\n"
            "--\n"
            "-- Indexes declared with `index:` on a field. create_db_and_tables()\n"
            "-- already builds these on a fresh database; apply this file to one that\n"
            "-- already exists:\n"
            "--\n"
            '--     psql "$DATABASE_URL" -f indexes.sql\n'
            "--\n"
            "-- Idempotent, and create-only: removing a declaration drops nothing.\n"
        )
        if not self.specs:
            return header + "--\n-- No indexes are declared in these schemas.\n"
        return header + "\n" + "\n".join(self.statements()) + "\n"

    def save(self, filepath: str | PathLike):
        self.logger.info(f"Saving index DDL to {filepath}")
        with open(filepath, "w") as file:
            file.write(self.render())
