services:
  windows:
    image: ghcr.io/dockur/windows
    environment:
      VERSION: "${WINDOWS_VERSION:-11}"
      RAM_SIZE: "${RAM_SIZE:-4G}"
      CPU_CORES: "${CPU_CORES:-2}"
      DISK_SIZE: "${DISK_SIZE:-64G}"
      USERNAME: "${WIN_USERNAME:-User}"
      PASSWORD: "${WIN_PASSWORD:-test}"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - "${NOVNC_PORT:-8006}:8006"
      - "${RDP_PORT:-3389}:3389"
    volumes:
      - ./oem:/oem
      - ./oem:/data
      - windows-data:/storage
    stop_grace_period: 2m

volumes:
  windows-data:
