FROM python:3.12-slim
ARG PACKAGE_VERSION
WORKDIR /app
RUN pip install --no-cache-dir \
    "fastapifromfrictionless==${PACKAGE_VERSION}" \
    "uvicorn[standard]" \
    psycopg2-binary \
    geoalchemy2 \
    python-multipart \
    frictionless
